stages:
  - compile
  - build
compile:
  image: node:latest
  stage: compile
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn compile
    - yarn lint
build:
  image: docker:19.03.8
  stage: build
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - /^(\w+\.\w+)-(sprint\d+)(?>-((?>dev|fix|hotfix)\d+))?$/i
  services:
    - docker:19.03.8-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build ./ -t $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
