version: '3.7'
services:
  db:
    image: mongo
    networks:
      backend:
        aliases:
          - db-testing
    ports:
      - 27017
    volumes:
      - db:/my/own/datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: avikast
  backend:
    image: avikast-backend
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 3080:3080
      - 3443:3443
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: avikast
volumes:
  db:
networks:
  backend:
