version: '3.7'
services:
  db:
    image: mongo
    networks:
      backend:
        aliases:
          - db-testing
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: avikast
      MONGO_INITDB_ROOT_PASSWORD: admin
  backend:
    image: avikast-backend
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 3080:3080
      - 3443:3443
    environment:
      NODE_ENV: testing
volumes:
  db:
networks:
  backend:
