version: '3.7'

services:
  db:
    image: mongo
    ports:
      - 5432:5432
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: avikast
volumes:
  db:
