version: '3.7'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: avikast
      MONGO_INITDB_ROOT_PASSWORD: admin
volumes:
  db:
